import { Appointment, Doctor, KanbanColumn } from './types';

const TODAY = new Date().toISOString().slice(0, 10);

export const COLUMNS: KanbanColumn[] = [
  { id: 'waiting', title: 'Записи', color: '#6B7280', bgColor: '#F9FAFB' },
  { id: 'queue', title: 'Живая очередь', color: '#3B82F6', bgColor: '#EFF6FF' },
  { id: 'reception', title: 'Сейчас на приёме', color: '#10B981', bgColor: '#ECFDF5' },
  { id: 'done', title: 'Закончили', color: '#8B5CF6', bgColor: '#F5F3FF' },
];

export const initialAppointments: Appointment[] = [
  {
    id: '1',
    patientName: 'Рахимов Д.Н.',
    doctor: 'Омонов С.Р.',
    cabinet: 'Кабинет 12',
    time: '09:00',
    date: TODAY,
    direction: 'Терапия',
    service: 'Осмотр',
    status: 'waiting',
  },
  {
    id: '2',
    patientName: 'Рахимов Д.Н.',
    doctor: 'Омонов С.Р.',
    cabinet: 'Кабинет 12',
    time: '09:30',
    date: TODAY,
    direction: 'Хирургия',
    service: 'Консультация',
    status: 'waiting',
  },
  {
    id: '3',
    patientName: 'Рахимов Д.Н.',
    doctor: 'Омонов С.Р.',
    cabinet: 'Кабинет 12',
    time: '10:00',
    date: TODAY,
    direction: 'Терапия',
    service: 'УЗИ',
    status: 'waiting',
  },
  {
    id: '4',
    patientName: 'Рахимов Д.Н.',
    doctor: 'Омонов С.Р.',
    cabinet: 'Кабинет 12',
    time: '10:30',
    date: TODAY,
    direction: 'Кардиология',
    service: 'ЭКГ',
    status: 'waiting',
  },
  {
    id: '5',
    patientName: 'Рахимов Д.Н.',
    doctor: 'Омонов С.Р.',
    cabinet: 'Кабинет 12',
    time: '11:00',
    date: TODAY,
    direction: 'Терапия',
    service: 'Анализы',
    status: 'waiting',
  },
  {
    id: '6',
    patientName: 'Рахимов Д.Н.',
    doctor: 'Омонов С.Р.',
    cabinet: 'Кабинет 12',
    time: '11:30',
    date: TODAY,
    direction: 'Хирургия',
    service: 'Перевязка',
    status: 'waiting',
  },

  {
    id: '7',
    patientName: 'Рахимов Д.Н.',
    doctor: 'Омонов С.Р.',
    cabinet: 'Кабинет 12',
    time: '09:00',
    date: TODAY,
    discount: 'Оплачено: 09:30',
    direction: 'Терапия',
    service: 'Осмотр',
    status: 'queue',
  },
  {
    id: '8',
    patientName: 'Рахимов Д.Н.',
    doctor: 'Омонов С.Р.',
    cabinet: 'Кабинет 12',
    time: '09:30',
    date: TODAY,
    discount: 'Оплачено: 10:00',
    direction: 'Хирургия',
    service: 'Консультация',
    status: 'queue',
  },
  {
    id: '9',
    patientName: 'Рахимов Д.Н.',
    doctor: 'Омонов С.Р.',
    cabinet: 'Кабинет 12',
    time: '10:00',
    date: TODAY,
    discount: 'Оплачено: 09:36',
    direction: 'Кардиология',
    service: 'ЭКГ',
    status: 'queue',
  },

  {
    id: '10',
    patientName: 'Рахимов Д.Н.',
    doctor: 'Омонов С.Р.',
    cabinet: 'Кабинет 12',
    time: '09:00',
    date: TODAY,
    discount: 'Длительность: 09:35',
    direction: 'Терапия',
    service: 'Осмотр',
    status: 'reception',
  },

  {
    id: '11',
    patientName: 'Рахимов Д.Н.',
    doctor: 'Омонов С.Р.',
    cabinet: 'Кабинет 12',
    time: '09:00',
    date: TODAY,
    direction: 'Терапия',
    service: 'Осмотр',
    status: 'done',
  },
  {
    id: '12',
    patientName: 'Рахимов Д.Н.',
    doctor: 'Омонов С.Р.',
    cabinet: 'Кабинет 12',
    time: '09:30',
    date: TODAY,
    direction: 'Хирургия',
    service: 'Консультация',
    status: 'done',
  },
  {
    id: '13',
    patientName: 'Рахимов Д.Н.',
    doctor: 'Омонов С.Р.',
    cabinet: 'Кабинет 12',
    time: '10:00',
    date: TODAY,
    direction: 'Кардиология',
    service: 'ЭКГ',
    status: 'done',
  },
];

export const doctors: Doctor[] = [
  {
    id: 'd1',
    name: 'Омонов С.Р.',
    specialty: 'врач · терапевт',
    arrivalTime: '09:05',
    departureTime: '18:21',
    recordsCount: 15,
    queueCount: 5,
    completedCount: 3,
    doctorStatus: 'На операции',
  },
  {
    id: 'd2',
    name: 'Омонов С.В.',
    specialty: 'врач · хирург',
    arrivalTime: '09:05',
    departureTime: '18:21',
    recordsCount: 16,
    queueCount: 5,
    completedCount: 3,
    doctorStatus: 'Обед',
  },
  {
    id: 'd3',
    name: 'Омонов С.В.',
    specialty: 'врач · терапевт',
    arrivalTime: '08:50',
    departureTime: '18:21',
    recordsCount: 15,
    queueCount: 5,
    completedCount: 3,
    doctorStatus: 'На приёме',
  },
  {
    id: 'd4',
    name: 'Омонов С.В.',
    specialty: 'врач · хирург',
    arrivalTime: '09:00',
    departureTime: '18:21',
    recordsCount: 15,
    queueCount: 5,
    completedCount: 3,
    doctorStatus: 'Закрыть очередь',
  },
  {
    id: 'd5',
    name: 'Омонов С.В.',
    specialty: 'врач · терапевт',
    arrivalTime: '09:00',
    departureTime: '18:21',
    recordsCount: 15,
    queueCount: 5,
    completedCount: 3,
    doctorStatus: 'Отпуск',
  },
  {
    id: 'd6',
    name: 'Омонов С.В.',
    specialty: 'врач · хирург',
    arrivalTime: '09:00',
    departureTime: '18:21',
    recordsCount: 15,
    queueCount: 5,
    completedCount: 3,
    doctorStatus: 'Не пришел',
  },
];
